var pynchon = {
  'nodes': [
    {'nodeName': 'Thomas Pynchon', group: 1},
    {'nodeName': 'Henry Adams', group: 1},
    {'nodeName': 'Ludwig Wittgenstein', group: 1},
    {'nodeName': 'Vladimir Nabokov', group: 1},
    {'nodeName': 'Giorgio de Chirico', group: 1},
    {'nodeName': 'Emily Dickinson', group: 1},
    {'nodeName': 'William March', group: 1},
    {'nodeName': 'Rainer Maria Rilke', group: 1},
    {'nodeName': 'Jorge Luis Borges', group: 1},
    {'nodeName': 'Ishmael Reed', group: 1},
    {'nodeName': 'Ralph Waldo Emerson', group: 1},
    {'nodeName': 'Patrick O\'Brien', group: 1},
    {'nodeName': 'Umberto Eco', group: 1},
    {'nodeName': 'François Rabelais', group: 1},
    {'nodeName': 'Miguel de Cervantes', group: 1},
    {'nodeName': 'Laurence Sterne', group: 1},
    {'nodeName': 'Edgar Allan Poe', group: 1},
    {'nodeName': 'Laurence Sterne', group: 1},
    {'nodeName': 'Nathaniel Hawthorne', group: 1},
    {'nodeName': 'Herman Melville', group: 1},
    {'nodeName': 'Charles Dickens', group: 1},
    {'nodeName': 'Joseph Conrad', group: 1},
    {'nodeName': 'Thomas Mann', group: 1},
    {'nodeName': 'William S. Burroughs', group: 1},
    {'nodeName': 'Ralph Ellison', group: 1},
    {'nodeName': 'Patrick White', group: 1},
    {'nodeName': 'Toni Morrison', group: 1},
    {'nodeName': 'James Joyce', group: 1},
    {'nodeName': 'E.M. Forster', group: 1},
    {'nodeName': 'Robert Musil', group: 1},
    {'nodeName': 'John Dos Passos', group: 1},
    {'nodeName': 'Jack Kerouac', group: 1},
    {'nodeName': 'T.S. Eliot', group: 1},
    {'nodeName': 'Ernest Hemingway', group: 1},
    {'nodeName': 'Henry Miller', group: 1},
    {'nodeName': 'Saul Bellow', group: 1},
    {'nodeName': 'Herbert Gold', group: 1},
    {'nodeName': 'Philip Roth', group: 1},
    {'nodeName': 'Norman Mailer', group: 1},
    {'nodeName': 'John Buchan', group: 1},
    {'nodeName': 'Graham Greene', group: 1},
    {'nodeName': 'Helen Waddell', group: 1},
    {'nodeName': 'Norbert Wiener', group: 1}
  ],

  links: [
    {'source': 1, 'target': 0},
    {'source': 2, 'target': 0},
    {'source': 3, 'target': 0},
    {'source': 4, 'target': 0},
    {'source': 5, 'target': 0},
    {'source': 6, 'target': 0},
    {'source': 8, 'target': 0},
    {'source': 9, 'target': 0},
    {'source': 10, 'target': 0},
    {'source': 11, 'target': 0},
    {'source': 12, 'target': 0},
    {'source': 13, 'target': 0},
    {'source': 14, 'target': 0},
    {'source': 15, 'target': 0},
    {'source': 16, 'target': 0},
    {'source': 17, 'target': 0},
    {'source': 18, 'target': 0},
    {'source': 19, 'target': 0},
    {'source': 20, 'target': 0},
    {'source': 21, 'target': 0},
    {'source': 22, 'target': 0},
    {'source': 23, 'target': 0},
    {'source': 24, 'target': 0},
    {'source': 25, 'target': 0},
    {'source': 26, 'target': 0},
    {'source': 27, 'target': 0},
    {'source': 28, 'target': 0},
    {'source': 29, 'target': 0},
    {'source': 30, 'target': 0},
    {'source': 31, 'target': 0},
    {'source': 32, 'target': 0},
    {'source': 33, 'target': 0},
    {'source': 34, 'target': 0},
    {'source': 35, 'target': 0},
    {'source': 36, 'target': 0},
    {'source': 37, 'target': 0},
    {'source': 38, 'target': 0},
    {'source': 39, 'target': 0},
    {'source': 40, 'target': 0},
    {'source': 41, 'target': 0},
    {'source': 42, 'target': 0}
  ]
};