var pynchon = {
  'nodes': [
    {'nodeName': 'Henry Adams', group: 1},
    {'nodeName': 'Ludwig Wittgenstein', group: 1},
    {'nodeName': 'Vladimir Nabokov', group: 1},
    {'nodeName': 'Giorgio de Chirico', group: 1},
    {'nodeName': 'Emily Dickinson', group: 1},
    {'nodeName': 'William March', group: 1},
    {'nodeName': 'Rainer Maria Rilke', group: 1},
    {'nodeName': 'Jorge Luis Borges', group: 1},
    {'nodeName': 'Ishmael Reed', group: 1},
    {'nodeName': 'Ralph Waldo Emerson', group: 1},
    {'nodeName': 'Patrick O\'Brien', group: 1},
    {'nodeName': 'Umberto Eco', group: 1},
    {'nodeName': 'François Rabelais', group: 1},
    {'nodeName': 'Miguel de Cervantes', group: 1},
    {'nodeName': 'Laurence Sterne', group: 1},
    {'nodeName': 'Edgar Allan Poe', group: 1},
    {'nodeName': 'Laurence Sterne', group: 1},
    {'nodeName': 'Nathaniel Hawthorne', group: 1},
    {'nodeName': 'Herman Melville', group: 1},
    {'nodeName': 'Charles Dickens', group: 1},
    {'nodeName': 'Joseph Conrad', group: 1},
    {'nodeName': 'Thomas Mann', group: 1},
    {'nodeName': 'William S. Burroughs', group: 1},
    {'nodeName': 'Ralph Ellison', group: 1},
    {'nodeName': 'Patrick White', group: 1},
    {'nodeName': 'Toni Morrison', group: 1},
    {'nodeName': 'James Joyce', group: 1},
    {'nodeName': 'E.M. Forster', group: 1},
    {'nodeName': 'Robert Musil', group: 1},
    {'nodeName': 'John Dos Passos', group: 1},
    {'nodeName': 'Jack Kerouac', group: 1},
    {'nodeName': 'T.S. Eliot', group: 1},
    {'nodeName': 'Ernest Hemingway', group: 1},
    {'nodeName': 'Henry Miller', group: 1},
    {'nodeName': 'Saul Bellow', group: 1},
    {'nodeName': 'Herbert Gold', group: 1},
    {'nodeName': 'Philip Roth', group: 1},
    {'nodeName': 'Norman Mailer', group: 1},
    {'nodeName': 'John Buchan', group: 1},
    {'nodeName': 'Graham Greene', group: 1},
    {'nodeName': 'Helen Waddell', group: 1},
    {'nodeName': 'Norbert Wiener', group: 1},
    {'nodeName': 'Thomas Pynchon', group: 1},
    {'nodeName': 'David Foster Wallace', group: 2},
    {'nodeName': 'William Vollmann', group: 2},
    {'nodeName': 'Richard Powers', group: 2},
    {'nodeName': 'Steve Erickson', group: 2},
    {'nodeName': 'David Mitchell', group: 2},
    {'nodeName': 'Neal Stephenson', group: 2},
    {'nodeName': 'Dave Eggers', group: 2},
    {'nodeName': 'Tommaso Pincio', group: 2},
    {'nodeName': 'T. Coraghessan Boyle', group: 2},
    {'nodeName': 'Don DeLillo', group: 2},
    {'nodeName': 'Ian Rankin', group: 2},
    {'nodeName': 'William Gibson', group: 2},
    {'nodeName': 'Elfriede Jelinek', group: 2},
    {'nodeName': 'Rick Moody', group: 2},
    {'nodeName': 'Alan Moore', group: 2},
    {'nodeName': 'Arturo Pérez-Reverte', group: 2},
    {'nodeName': 'Richard Powers', group: 2},
    {'nodeName': 'Salman Rushdie', group: 2},
    {'nodeName': 'Neal Stephenson', group: 2},
    {'nodeName': 'Bruce Sterling', group: 2},
    {'nodeName': 'Jan Wildt', group: 2},
    {'nodeName': 'Laurie Anderson', group: 2},
    {'nodeName': 'Zak Smith', group: 2},
    {'nodeName': 'David Cronenberg', group: 2},
    {'nodeName': 'Paul Thomas Anderson', group: 2},
    {'nodeName': 'James Murphy', group: 2},
    {'nodeName': 'Adam Rapp', group: 2},
    {'nodeName': 'Zadie Smith', group: 2}
  ],

  links: [
    {'source': 0, 'target': 42},
    {'source': 1, 'target': 42},
    {'source': 2, 'target': 42},
    {'source': 3, 'target': 42},
    {'source': 4, 'target': 42},
    {'source': 5, 'target': 42},
    {'source': 6, 'target': 42},
    {'source': 8, 'target': 42},
    {'source': 9, 'target': 42},
    {'source': 10, 'target': 42},
    {'source': 11, 'target': 42},
    {'source': 12, 'target': 42},
    {'source': 13, 'target': 42},
    {'source': 14, 'target': 42},
    {'source': 15, 'target': 42},
    {'source': 16, 'target': 42},
    {'source': 17, 'target': 42},
    {'source': 18, 'target': 42},
    {'source': 19, 'target': 42},
    {'source': 20, 'target': 42},
    {'source': 21, 'target': 42},
    {'source': 22, 'target': 42},
    {'source': 23, 'target': 42},
    {'source': 24, 'target': 42},
    {'source': 25, 'target': 42},
    {'source': 26, 'target': 42},
    {'source': 27, 'target': 42},
    {'source': 28, 'target': 42},
    {'source': 29, 'target': 42},
    {'source': 30, 'target': 42},
    {'source': 31, 'target': 42},
    {'source': 32, 'target': 42},
    {'source': 33, 'target': 42},
    {'source': 34, 'target': 42},
    {'source': 35, 'target': 42},
    {'source': 36, 'target': 42},
    {'source': 37, 'target': 42},
    {'source': 38, 'target': 42},
    {'source': 39, 'target': 42},
    {'source': 40, 'target': 42},
    {'source': 41, 'target': 42},
    {'source': 43, 'target': 42},
    {'source': 44, 'target': 42},
    {'source': 45, 'target': 42},
    {'source': 46, 'target': 42},
    {'source': 47, 'target': 42},
    {'source': 48, 'target': 42},
    {'source': 49, 'target': 42},
    {'source': 50, 'target': 42},
    {'source': 51, 'target': 42},
    {'source': 52, 'target': 42},
    {'source': 53, 'target': 42},
    {'source': 54, 'target': 42},
    {'source': 55, 'target': 42},
    {'source': 56, 'target': 42},
    {'source': 57, 'target': 42},
    {'source': 58, 'target': 42},
    {'source': 59, 'target': 42},
    {'source': 60, 'target': 42},
    {'source': 61, 'target': 42},
    {'source': 62, 'target': 42},
    {'source': 63, 'target': 42},
    {'source': 64, 'target': 42},
    {'source': 65, 'target': 42},
    {'source': 66, 'target': 42},
    {'source': 67, 'target': 42},
    {'source': 68, 'target': 42},
    {'source': 69, 'target': 42},
    {'source': 70, 'target': 42}
  ]
};